### ISSUE TITLE
Dual Boot. Partition is gone. 

### ISSUE THREAD

**Issue by igormclven** [jsassu20/Lenovo-ThinkPad-T450-Mojave#14]
hey! I'm here again! xd I have a problem right now and that is that after the EFI update to 3.0 the mac partition is not recognized. I thought it was some APFS driver problem but it doesn't work.

I'm trying previous versions of EFI but the partition doesn't appear. From windows with paragon the partition is accessible without problems. I'm running out of ideas. 

Any idea will be greatly appreciated.

**Comment by jianzhao0806** [comment]
Maybe you delete the Mac OS depended partition, maybe preboot .By the way, how about your external monitor?

**Comment by igormclven** [comment]
I had to do a clean reinstatement. Right now I am reviewing the problems with the hearing aids. The dual monitor is now working properly.

**Comment by igormclven** [comment]
And you, how could you solve the problem with the headphones?

**Comment by jianzhao0806** [comment]
wait

**Comment by jianzhao0806** [comment]
https://www.elitemacx86.com/threads/fix-audio-distortion-when-using-headphones-on-laptops.185/page-3
Not perfect, but works well

**Comment by jianzhao0806** [comment]
> > Maybe you delete the Mac OS depended partition, maybe preboot .By the way, how about your external monitor?
> 
> And you, how could you solve the problem with the headphones?

You can have a try, if you have a good way ,please tell me,thank you! :-)
