### ISSUE TITLE
wifi networks not detected win10

### ISSUE THREAD

**Issue by roibudoru** [jsassu20/Lenovo-ThinkPad-T450-Mojave#17]
I just installed the bcm4360 card  and everything is working in Mojave but after booting in win 10 I noticed that the wifi is not working even after installing the provided drivers...

**Comment by svobluk** [comment]
try boot camp drivers

**Comment by roibudoru** [comment]
already did that

**Comment by igormclven** [comment]
If there is a compatibility issue, check the version of Windows you are using and that all drivers are up to date. But clearly it is a Windows problem, and opening an issue of it here is not appropriate because it has nothing to do with the Hackintosh setup.

**Comment by lhaus** [comment]
Same issue here, in linux too. Card detected but no networks found.

**Comment by jsassu20** [comment]
You need the wifi drivers I have in the utilities folder. Its all labeled

**Comment by jsassu20** [comment]
> If there is a compatibility issue, check the version of Windows you are using and that all drivers are up to date. But clearly it is a Windows problem, and opening an issue of it here is not appropriate because it has nothing to do with the Hackintosh setup.

It's all good buddy, I appreciate where you're coming from on the comment but I encourage all questions no matter what they pertain to! Thank you though, I'm not being a dick so I hope it doesn't come off that way!

**Comment by jsassu20** [comment]
Even though dual a triple booting is possible (I have had 4 operating systems installed on my machine in the past with no issues) I seriously recommend opting for using macOS as the main OS and then running any other OS you might need from within VMWare Fusion (or Virtualbox if you don't have cash for VMWare, its just as good). When you install the AirPort card and get your system running, it's essentially a real Mac in terms of the functionality its capable of. Running other OS from a virtual environment is very stable so long as you have an ssd and 8GB of ram (4 can work too but 8 or 16 is def a better idea). You will have all of the features you get from dual booting and the ability to seamlessly move between OS windows by swiping left or right with 4 fingers. But its your call.

**Comment by igormclven** [comment]
What a great attitude!, great, in tonymac or insanely are somewhat problematic when the themes come out of center, it was habit xd . Thank you for your effort.

In other things I tell you that is on its way to me, a controller to unlock the bios and a ngff adapter for a BCM9432 card (Although I do not know if the latter works well ... is a little old). What do you think?

**Comment by roibudoru** [comment]
> You need the wifi drivers I have in the utilities folder. Its all labeled

I did that , thats why i am asking about here.I didnt want to be rude or something like that im just reporting the problem i am facing ...

**Comment by svobluk** [comment]
Which card do you have? Exact card type please? I have bcm943602cs and attached drivers didnt work for me as well, boot camp neither, anyway I have found another one which works, bt+wifi.

**Comment by roibudoru** [comment]
I am using a BCM94360CSAX just like the recomandation from this  guide ,could you please share  your drivers  ?

**Comment by svobluk** [comment]
check and try DriverPack Solution, if any will work, you can uninstall this SW afterwards..

**Comment by jsassu20** [comment]
The drivers are in the utilities folder under airport drivers

**Comment by roibudoru** [comment]
unfortunatly the drivers in the utilities  folder are not working for me  ,

> The drivers are in the utilities folder under airport drivers

**Comment by roibudoru** [comment]
> check and try DriverPack Solution, if anyone will work, you can uninstall this SW afterwards..
I did that  but  still no luck i tryed all 5 or 6 versions ...what  version of the  driver are  you using?

**Comment by igormclven** [comment]
Try Driver Booster, generally it install the most recent drivers. Maybe work :3

**Comment by svobluk** [comment]
> > check and try DriverPack Solution, if anyone will work, you can uninstall this SW afterwards..
> > I did that  but  still no luck i tryed all 5 or 6 versions ...what  version of the  driver are  you using?

the driver i have from DriverPack is version 1.558.53.15 (Broadcom 802.11ac Wireless PCIE Full Dongle Adapter. Device ID is VEN_14E4&DEV_43BA
