### ISSUE TITLE
Error loading kernel cache (0x9)

### ISSUE THREAD

**Issue by costadaniel** [jsassu20/Lenovo-ThinkPad-T450-Mojave#18]
I have copy all the files from the repo to the CLOVER folder in USB Drive.
![image](https://user-images.githubusercontent.com/29005546/64539676-4b150500-d2f5-11e9-9fe0-03706c2715aa.png)

![image](https://user-images.githubusercontent.com/29005546/64539714-5cf6a800-d2f5-11e9-8db4-1bfe46b29a81.png)

So im having this error message:

![IMG_20190909_112244](https://user-images.githubusercontent.com/29005546/64539478-eeb1e580-d2f4-11e9-81dd-bb56da56ce48.jpg)

**Comment by sam-anam1** [comment]
try to rename file CLOVERX64.efi to BOOTX64.efi in [BOOT] folder

**Comment by costadaniel** [comment]
> try to rename file CLOVERX64.efi to BOOTX64.efi in [BOOT] folder

Works fine! Thanks @sam-anam1 ! Now i have this error:
Before:
![IMG_20190909_115749](https://user-images.githubusercontent.com/29005546/64565381-fe97ec80-d329-11e9-8574-d7c4acb29ea8.jpg)

After:
![IMG_20190909_172954](https://user-images.githubusercontent.com/29005546/64565341-e88a2c00-d329-11e9-95b7-6c667856ec3c.jpg)
