### ISSUE TITLE
Add new ram could't boot system

### ISSUE THREAD

**Issue by RoWe98** [jsassu20/Lenovo-ThinkPad-T450-Mojave#21]
It was one ddr3l 1600 8G ram on my computer, while I bought one another ddr3L 1600 8G ram and added it on the computer but the Hackintosh couldn't boot.
It just shows the white apple logo and quickly restart when I select the option "boot macOS from Hackintosh HD"

**Comment by Zardinality** [comment]
@RoWe98 Hi, sorry if bothers you. How much is the ram size shown by the system info in your case? I also did an 8g-ram upgrade and it shows now I have 16G ram, which is not true(8G+4G soldered onboard). Any information is appreciated!
