### ISSUE TITLE
NGFF A/E adapter information

### ISSUE THREAD

**Issue by hetsch** [jsassu20/Lenovo-ThinkPad-T450-Mojave#22]
Hi @jsassu20,

first I want to thank you for this incredible useful repository. Works out of the box on my machine! The only question that is left on my side is what NGFF A/E adapter you used for the BCM94360CSAX card. I'm a little bit scared about the space constraints inside the laptop body. The one that seems to be ok is this one https://www.aliexpress.com/item/32860559726.html?spm=a2g0o.cart.0.0.72c43c00nhBSkA&mp=1. It would be very useful if you can give any advice or a link to the adapter what you've bought.

Thank's a bunch for all the work you've done!

**Comment by jsassu20** [comment]
No problem, I’m glad it all worked for you!

For the adapter I don’t see why pretty much anyone wouldn’t work in there but just to give you some reassurance that you’ll be able to just buy one that fits for sure it’s linked below.

Hobbypower BCM94360CS2/BCM943224PCIEBT2 Card To NGFF(M.2) Key A/E Adapter For Mac OS https://www.amazon.com/dp/B01KHRJVXW/ref=cm_sw_r_cp_api_i_2o7LDbKZP042Q
![Screenshot 2019-10-04 at 5 07 46 PM](https://user-images.githubusercontent.com/12767985/66240097-a0142300-e6c9-11e9-94c5-829b71f0e3a2.png)

**Comment by hetsch** [comment]
Oh man, thank's for sharing all the information! I think I give the China card and the adapter a shot and see how far it works. Other options are fare more expensive in Europe. I report back if you like. Closing it now because you've more than fully answered my question.

**Comment by buraktamturk** [comment]
@hetsch Did it worked with the adapter and card combo you mentioned?

**Comment by hetsch** [comment]
@buraktamturk Still waiting for the delivery from China :). I'll keep you informed how it worked out.

**Comment by JalenSpringfield** [comment]
> FYI
> 
> There are actual airport cards which Apple uses in official Apple hardware and then there are other available options with the same chipset that functions inside of Apple hardware but comes from some third-party

Hey @jsassu20, I apologize for re-opening the issue. I’m looking for an airport card myself for a desktop build. I’ve been researching quite extensively to determine how to get a genuine card. Is there any way to tell besides buying a MacBook? Or are there reputable shops that part out Macs? Thanks!

**Comment by jsassu20** [comment]
https://www.ebay.com/itm/Genuine-Apple-Broadcom-BCM94360CD-802-11ac-Mac-WiFi-Bluetooth-4-0-Card/373071430508?hash=item56dcca436c:g:8FYAAOSwAVhe0WkZ

https://www.ebay.com/itm/BCM94360CD-BCM94331CD-WIFI-WLAN-module-to-PCI-e-1x-16x-Desktop-PC-WIFI-adapter/283570759510?_trkparms=aid%3D1110006%26algo%3DHOMESPLICE.SIM%26ao%3D1%26asc%3D20200520130830%26meid%3Dceadda4db4ce4e149a9fece144ae5cec%26pid%3D101195%26rk%3D9%26rkt%3D12%26mehot%3Dag%26sd%3D373071430508%26itm%3D283570759510%26pmt%3D1%26noa%3D0%26pg%3D2047675%26algv%3DSimplAMLv5PairwiseWebWithBBEV2bDemotion&_trksid=p2047675.c101195.m1851

There you go boss you cann use osxwifi but they rip you off this same configuration is 150 there

**Comment by jsassu20** [comment]
![s-l1600](https://user-images.githubusercontent.com/12767985/85153956-d1fff200-b224-11ea-93ef-c94ba734f22e.jpg)

**Comment by JalenSpringfield** [comment]
Thanks so much!

**Comment by jsassu20** [comment]
> > FYI
> > There are actual airport cards which Apple uses in official Apple hardware and then there are other available options with the same chipset that functions inside of Apple hardware but comes from some third-party
> 
> Hey @jsassu20, I apologize for re-opening the issue. I’m looking for an airport card myself for a desktop build. I’ve been researching quite extensively to determine how to get a genuine card. Is there any way to tell besides buying a MacBook? Or are there reputable shops that part out Macs? Thanks!

https://www.amazon.com/Broadcom-BCM94360CD-BCM4360CD-Bluetooth-Huasijie/dp/B00L35XSMS

and this 

https://www.amazon.com/Shaluoman-BCM94360CD-BCM94331CD-PCI-Adapter/dp/B0762N2R2R/ref=pd_sbs_147_4/147-8164608-0670207?_encoding=UTF8&pd_rd_i=B0762N2R2R&pd_rd_r=33a0854b-9637-4fd7-a6dc-e7dafb164e64&pd_rd_w=WWRAc&pd_rd_wg=WAOEm&pf_rd_p=b65ee94e-1282-43fc-a8b1-8bf931f6dfab&pf_rd_r=J6FQPTWCMAJW69J8S13Q&psc=1&refRID=J6FQPTWCMAJW69J8S13Q

You can prob get the airport card cheaper used on ebay i think i got mine for 40 bucks. I have 2 extra adapters for this card too if you need one ill mail you it.
