### ISSUE TITLE
Tested release 2.2

### ISSUE THREAD

**Issue by svobluk** [jsassu20/Lenovo-ThinkPad-T450-Mojave#6]
Hello, 

I have just tested release v1.6, I have seen following issues so far:

- LiluFriend is not loading due to DiskArbitrationFixup and SMCSuperIO are not part of the kext folder anymore - eg. No kexts found for these libraries: fish.goldfish64.DiskArbitrationFixup, ru.joedm.SMCSuperIO. Seems they are still part of LiluFriend.kext/Contents/Info.plist.

- X86PlatformPluginInjector not loading as well ??

- PowerNap option is gone. v1.4 was fine.

**Comment by jsassu20** [comment]
try 1.8

**Comment by svobluk** [comment]
tried v1.8. unfortunately X86PlatformPluginInjector and PowerNap "issues" still persist. Just letting you know, maybe I'll investigate myself when I have time. It's not super urgent, elswhere I do not see any issues.

**Comment by jsassu20** [comment]
Ok great thank you for letting me know Ill get it on the new update gimme a few days.

**Comment by svobluk** [comment]
tested release 2.2 and power nap is back. THX!

identified following issues within v2.2
- appleps2smarttouchpad is not working on T450 touchpad (replaced with VoodooPS2Controller and SSDT-VPS2 patch instead of SSDT-ASTP
- drivers64uefi folder is missing audiodxe-64.efi for proper startup sound
- config.plist is missing mobile option checked in SMBIOS, without that I'm missing battery options at power saving settings tab.
